Block templates Db and Reactors
SEMOSS/semoss pull request #255
Opened 2024-11-21 20:51 UTC by shivanshpatel13

WIP

2025-02-05 19:24 UTC, ppatel9703 commented
@themaherkhalil  i've looked it over and it looks good to me. This will be iterated upon in further updates. 
When you get the chance pls review as well

2025-05-07 15:18 UTC, ppatel9703 commented
Converting to Draft as FE has asked for changes 
Once Kanini has changes will mark ready for review

2025-05-15 18:56 UTC, EJV20 requested changes

2025-05-15 18:56 UTC, EJV20 commented on src/prerna/sablecc2/om/ReactorKeysEnum.java
> +	WIDTH("width", 											    "The width to use for screenshot capture"),
Why isn't this placed alphabetically?

2025-05-16 17:53 UTC, EJV20 approved these changes
We need to create a new ticket to uncomment out other reactors

2025-05-16 17:53 UTC, EJV20 commented on src/prerna/reactor/blocks/EditBlockReactor.java
> +//import java.util.Map;
Why is this commented out, but listed as a requirement

2025-05-16 17:53 UTC, EJV20 commented on src/prerna/reactor/blocks/GetBlockReactor.java
> +//
why is this commented out?

2025-05-16 17:53 UTC, EJV20 commented on src/prerna/theme/BlocksThemeUtils.java
> +//
why is this commented out?

2025-05-19 15:26 UTC, ryanweiler92 commented
There is a ton of commented code in this PR. Can we remove this or this here for a reason?

2025-05-19 15:28 UTC, rithvik-doshi commented on src/prerna/reactor/blocks/GetBlockReactor.java
> +//
Potentially needed for future functionality and didn't want to start from scratch when necessary. I'd defer to @johbaxter on whether to keep these reactors or delete them

2025-05-19 15:30 UTC, rithvik-doshi commented on src/prerna/theme/BlocksThemeUtils.java
> +//
Not in use, this can be deleted

2025-05-19 15:30 UTC, EJV20 commented on src/prerna/reactor/blocks/GetBlockReactor.java
> +//
@rithvik-doshi @ryanweiler92 if the code works. I would uncomment it out.

2025-05-19 15:40 UTC, ppatel9703 commented
There was an additional change required this morning by JB- Marking this PR as a draft 
Kanini should have it in tomorrow -- want to hold off on the merge till then 

@ryanweiler92 @EJV20

2025-05-19 18:27 UTC, johbaxter commented
@samarthKharote 

Can you remove the 2 reactors by tomorrow?

![image](https://github.com/user-attachments/assets/f0f2ba61-1862-4244-aaef-e2d1181fe60a)

2025-05-20 13:30 UTC, samarthKharote commented
@johbaxter I have removed the `EditBlock` and `GetBlock` Reactors

2025-06-01 15:48 UTC, merged

2025-06-01 15:49 UTC, QodoAI-Agent commented
**Changelog updates:** 🔄

## 2025-06-01 [#255](https://github.com/SEMOSS/Semoss/pull/255)
### Added
- Blocks table support: initialization, default entries, and metadata (id, date_added, is_latest, is_deletable)
- Reactors for List, Get, Add, Edit, and Delete operations on blocks
### Changed
- Genericized reactor inputs and theme-DB handling; soft/hard delete support


>to commit the new content to the CHANGELOG.md file, please type:
>'/update_changelog --pr_update_changelog.push_changelog_changes=true'